# kube/base/secrets.yaml
# WARNING: for production, use sealed-secrets or external-secrets instead
apiVersion: v1
kind: Secret
metadata:
  name: mcp-router-db
type: Opaque
stringData:
  POSTGRES_DB: mcprouter
  POSTGRES_USER: mcprouter
  POSTGRES_PASSWORD: oK!1#7D*8tXc36ib
  DATABASE_URL: "postgresql+asyncpg://mcprouter:oK!1#7D*8tXc36ib@db:5432/mcprouter"
  JWT_SECRET: cda7HdUjXifYtsiadzU9TMYXFK5UKqsysil3uh7zkEktCJ4eaoQWwbObfE5yEOEv
  FERNET_KEY: "S_6-rWuHSPen1I5i1VviUuZlGiSueQ28g7y2BQ6yaX4="
